// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: p2pcachepb/v1/p2pcache.proto

package p2pcachepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_p2pcachepb_v1_p2pcache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2pcachepb_v1_p2pcache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_p2pcachepb_v1_p2pcache_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	MinuteQps     []byte                 `protobuf:"bytes,2,opt,name=minute_qps,json=minuteQps,proto3,oneof" json:"minute_qps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_p2pcachepb_v1_p2pcache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2pcachepb_v1_p2pcache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_p2pcachepb_v1_p2pcache_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetMinuteQps() []byte {
	if x != nil {
		return x.MinuteQps
	}
	return nil
}

var File_p2pcachepb_v1_p2pcache_proto protoreflect.FileDescriptor

const file_p2pcachepb_v1_p2pcache_proto_rawDesc = "" +
	"\n" +
	"\x1cp2pcachepb/v1/p2pcache.proto\x12\n" +
	"p2pcachepb\"4\n" +
	"\n" +
	"GetRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"e\n" +
	"\vGetResponse\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01\x12\"\n" +
	"\n" +
	"minute_qps\x18\x02 \x01(\fH\x01R\tminuteQps\x88\x01\x01B\b\n" +
	"\x06_valueB\r\n" +
	"\v_minute_qps2D\n" +
	"\n" +
	"GroupCache\x126\n" +
	"\x03Get\x12\x16.p2pcachepb.GetRequest\x1a\x17.p2pcachepb.GetResponseB\x1cZ\x1apeer2peer-cache/p2pcachepbb\x06proto3"

var (
	file_p2pcachepb_v1_p2pcache_proto_rawDescOnce sync.Once
	file_p2pcachepb_v1_p2pcache_proto_rawDescData []byte
)

func file_p2pcachepb_v1_p2pcache_proto_rawDescGZIP() []byte {
	file_p2pcachepb_v1_p2pcache_proto_rawDescOnce.Do(func() {
		file_p2pcachepb_v1_p2pcache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2pcachepb_v1_p2pcache_proto_rawDesc), len(file_p2pcachepb_v1_p2pcache_proto_rawDesc)))
	})
	return file_p2pcachepb_v1_p2pcache_proto_rawDescData
}

var file_p2pcachepb_v1_p2pcache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_p2pcachepb_v1_p2pcache_proto_goTypes = []any{
	(*GetRequest)(nil),  // 0: p2pcachepb.GetRequest
	(*GetResponse)(nil), // 1: p2pcachepb.GetResponse
}
var file_p2pcachepb_v1_p2pcache_proto_depIdxs = []int32{
	0, // 0: p2pcachepb.GroupCache.Get:input_type -> p2pcachepb.GetRequest
	1, // 1: p2pcachepb.GroupCache.Get:output_type -> p2pcachepb.GetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_p2pcachepb_v1_p2pcache_proto_init() }
func file_p2pcachepb_v1_p2pcache_proto_init() {
	if File_p2pcachepb_v1_p2pcache_proto != nil {
		return
	}
	file_p2pcachepb_v1_p2pcache_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2pcachepb_v1_p2pcache_proto_rawDesc), len(file_p2pcachepb_v1_p2pcache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_p2pcachepb_v1_p2pcache_proto_goTypes,
		DependencyIndexes: file_p2pcachepb_v1_p2pcache_proto_depIdxs,
		MessageInfos:      file_p2pcachepb_v1_p2pcache_proto_msgTypes,
	}.Build()
	File_p2pcachepb_v1_p2pcache_proto = out.File
	file_p2pcachepb_v1_p2pcache_proto_goTypes = nil
	file_p2pcachepb_v1_p2pcache_proto_depIdxs = nil
}
